### ISSUE TITLE
Ellipsis duplicate

### ISSUE THREAD

**Issue by jglovier** [primer/octicons#170] opened 2017-08-09 19:01 UTC
We've ended up with a duplicate of the `ellipsis` octicon somehow:

![image](https://user-images.githubusercontent.com/1319791/29139027-7aa72fb2-7d13-11e7-8956-160a48340b27.png)

One references `ellipsis`, the other `ellipses`, so I'm guessing this is simply a spelling error that was introduce somewhere?

- [`.octicon-ellipses`](https://octicons.github.com/icon/ellipses/)
- [`.octicon-ellipsis`](https://octicons.github.com/icon/ellipsis/)

**Comment by shurcooL** [comment] 2017-08-09 19:04
This looks like a duplicate of #159, which has already been resolved in #164.

**Closed** 2017-08-09 22:13 UTC

**Comment by jglovier** [comment] 2017-08-09 23:55
If it's resolved, how come it's still showing up on https://octicons.github.com/?

**Comment by shurcooL** [comment] 2017-08-10 00:48
Up until half an hour ago or so, the latest version was 5.0.1. The issue was resolved in master, which has very recently been made a part of 6.0.0 release by @jonrohan, see https://github.com/primer/octicons/pull/171.

Now that 6.0.0 is released and deployed, it's no longer on https://octicons.github.com/.
